name: trip_booking2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/images/cardView/
    - assets/images/medina/
    - assets/images/destination/
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans_ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Black.ttf
          weight: 900
